
class ArgsParser():
    def __init__(self,args):
        self._parse(args)

    def _parse(self, args):
        self.complex_pdb = args.complex_pdb
        self.serie_file = args.serie_file
        self.iterations = args.growing_steps
        self.criteria = args.criteria
        self.plop_path = args.plop_path
        self.sch_path = args.sch_path
        self.pele_dir = args.pele_dir
        self.contrl = args.contrl
        self.license = args.license
        self.resfold = args.resfold
        self.report = args.report
        self.traject = args.traject
        self.pdbout = args.pdbout
        self.cpus = args.cpus
        self.distcont = args.distcont
        self.threshold = args.threshold
        self.epsilon = args.epsilon
        self.condition = args.condition
        self.metricweights = args.metricweights
        self.nclusters = args.nclusters
        self.pele_eq_steps = args.pele_eq_steps
        self.restart = args.restart
        self.min_overlap = args.min_overlap
        self.max_overlap = args.max_overlap
        self.c_chain = args.c_chain
        self.f_chain = args.f_chain
        self.steps = args.steps
        self.temperature = args.temperature
        self.seed = args.seed
        self.rotamers = args.rotamers
        self.banned = args.banned
        self.limit = args.limit
        self.mae = args.mae
        self.rename = args.rename
        self.threshold_clash = args.clash_thr
        self.steering = args.steering
        self.translation_high = args.translation_high
        self.rotation_high = args.rotation_high
        self.translation_low = args.translation_low
        self.rotation_low = args.rotation_low
        self.explorative = args.explorative
        self.radius_box = args.radius_box
        self.sampling_control = args.sampling_control
        self.data = args.data
        self.documents = args.documents
        self.only_prepare = args.only_prepare
        self.only_grow = args.only_grow
        self.no_check = args.no_check
        self.debug = args.debug
        self.test = args.test
        self.cov_res = args.cov_res
        self.dist_constraint = args.dist_const
        self.constraint_core = args.constraint_core
        self.dih_constr = args.dih_constr
        self.protocol = args.protocol
        self.start_growing_from = args.st_from
        self.min_grow = args.min_grow
        self.min_sampling = args.min_sampling
        self.force_field = args.force_field
        self.dih_to_constraint = args.dihedrals_list
        self.srun = args.srun
        self.keep_templates = args.keep_templates

