name: Conda Install
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Include $CONDA in $PATH
      run: |
        echo ::add-path::$CONDA/bin
        echo ::add-path::$CONDA/condabin
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov codecov
    - name: Install via Conda
      run: |
        conda install -c NostrumBioDiscovery -c conda-forge frag_pele --yes 
    - name: Test with pytest
      run: |
        mkdir test_conda
        cd test_conda
        python -m frag_pele.main -h
