name: Conda Install
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      name: Conda setup
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: frag_env
        environment-file: conda_recipe/frag_env.yaml
        auto-activate-base: false

    - name: Environment Information
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Install frag_pele
      shell: bash -l {0}
      run: |
        python -m pip install --no-deps -v .

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        mkdir test_conda
        cd test_conda
        python -m frag_pele.main -h
