name: Conda Install
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      name: Conda setup
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: standard
        environment-file: devtools/envs/standard.yaml
        auto-activate-base: false

    - name: Environment Information
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov codecov

    - name: Install via Conda
      run: |
        conda env create -f conda_recipe/frag_env.yml
        
    - name: Install frag_pele
      run: |
        conda activate frag_env
        python -m pip install --no-deps -v .

    - name: Test with pytest
      run: |
        mkdir test_conda
        cd test_conda
        python -m frag_pele.main -h
